<?php
$fixo = 0;
$maximo_fixo = null;
$descricao_fixo = null;

$variado = 0;
$maximo_variado = null;
$descricao_variado = null;

$meta = 0;

if (!empty($this->view->geral[0])) {

    if ($this->view->geral[0]['tipo'] == 1) {
        $fixo = $this->view->geral[0]['valor'];

        foreach ($this->view->gastos as $key => $gastos) {
            if ($gastos['tipo'] == 'Fixo') {
                if (intval($gastos['valor']) > $maximo_fixo) {
                    $maximo_fixo = $gastos['valor'];
                    $descricao_fixo = $gastos['descricao'];
                }
            }
        }

        if (!empty($this->view->geral[1])) {
            $variado = $this->view->geral[1]['valor'];

            foreach ($this->view->gastos as $key => $gastos) {

                if ($gastos['tipo'] == 'Variado') {
                    if (intval($gastos['valor']) > $maximo_variado) {

                        $maximo_variado = $gastos['valor'];
                        $descricao_variado = $gastos['descricao'];
                    }
                }
            }
        }
    } else {
        $variado = $this->view->geral[0]['valor'];
        foreach ($this->view->gastos as $key => $gastos) {

            if (intval($gastos['valor']) > $maximo_variado) {
                $maximo_variado = $gastos['valor'];
                $descricao_variado = $gastos['descricao'];
            }
        }
    }

    if(!empty($this->view->meta)){
        $meta = $this->view->meta[0]['meta'];
    }
    
}
?>


<div class="container mt-5">

    <div class="row border-bottom p-3">

        <div class="col-auto">
            <h3 class=""><?php
                            if (empty($_POST)) {
                                $mes = date('m');
                            } else {
                                $mes = $_POST['mes'];
                            }
                            switch ($mes) {
                                case '01':
                                    $mes = 'Janeiro';
                                    break;
                                case '02':
                                    $mes = 'Fevereiro';
                                    break;
                                case '03':
                                    $mes = 'Março';
                                    break;
                                case '04':
                                    $mes = 'Abril';
                                    break;
                                case '05':
                                    $mes = 'Maio';
                                    break;
                                case '06':
                                    $mes = 'Junho';
                                    break;
                                case '07':
                                    $mes = 'Julho';
                                    break;
                                case '08':
                                    $mes = 'Agosto';
                                    break;
                                case '09':
                                    $mes = 'Setembro';
                                    break;
                                case '10':
                                    $mes = 'Outubro';
                                    break;
                                case '11':
                                    $mes = 'Novembro';
                                    break;
                                case '12':
                                    $mes = 'Dezembro';
                            };

                            echo $mes;
                            ?>
            </h3>
        </div>

        <div class="col-auto">
            <form action="/dashboard" method="post">
                <select class="form-select " name="mes">
                    <option class="text-center" value="">Mês</option>
                    <option value="01">Janeiro</option>
                    <option value="02">Fevereiro</option>
                    <option value="03" active>Março</option>
                    <option value="04">Abril</option>
                    <option value="05">Maio</option>
                    <option value="06">Junho</option>
                    <option value="07">Julho</option>
                    <option value="08">Agosto</option>
                    <option value="09">Setembro</option>
                    <option value="10">Outubro</option>
                    <option value="11">Novembro</option>
                    <option value="12">Dezembro</option>
                </select>
        </div>
        <div class="col-2 ">
            <button class="btn btn-secondary" type="submit">Selecionar</button>
        </div>
        </form>
    </div>

    <div class="row mt-3 p-2 border-bottom">

        <h5 class="text-center mt-2">Visão Geral</h5>


        <div class="col-sm-6 mt-5">
            <canvas id="myChart3"></canvas>
        </div>

        <div class="col-sm-5 offset-sm-1">
            <canvas id="myChart4"></canvas>
        </div>

        <div class="d-inline-flex">
            <div>
                <p class="text-center"> Gasto total:
                    <i>
                        <?php
                        if ($fixo != 0 || $variado != 0) {
                            echo 'R$' . $variado + $fixo;
                        } else {
                            echo 'Sem dados';
                        }
                        ?>
                    </i>
                </p>
            </div>
        </div>
        <div class="d-inline-flex">
            <p>Gasto faltante para estourar o teto:          
                    <i>
                        <?php
                        if ($fixo != 0 || $variado != 0) {
                            $total = $meta - ($variado + $fixo);
                            if ($total <= 0){?>
                                <p class="text-danger"> <?php echo ' R$ '.$total; ?></p>  
                            <?php } else { ?>
                                <p class="text-success"><?php echo ' R$ '.$total; ?></p>
                            <?php }                            
                        } else {
                            echo 'Sem dados';
                        }
                        ?>
                    </i>
                </p>
        </div>


    </div>

    <div class="row mt-4">
        <div class="col-6 border-end">
            <div>
                <h5 class="text-center">Gastos Fixos</h5>
                

                <canvas class="mt-4" id="myChart1"></canvas>

                <p class="mt-4">
                    Gasto total:
                    <?php
                    if ($fixo != 0) {
                        echo 'R$' . $fixo;
                    } else {
                        echo 'Sem dados';
                    }
                    ?>
                </p>
                <p>Maior gasto: <?php
                                if ($fixo != 0) {
                                    echo $maximo_fixo . ' em ' . $descricao_fixo;
                                } else {
                                    echo 'Sem dados';
                                }
                                ?></p>
            </div>
        </div>


        <div class="col-6">
            <h5>Gastos Variados</h5>
            

            <canvas class="mt-4" id="myChart2"></canvas>

            <p class="mt-4">
                Gasto total:
                <?php
                if ($variado != 0) {
                    echo 'R$' . $variado;
                } else {
                    echo 'Sem dados';
                }
                ?>
            </p>
            <p>Maior gasto: <?php
                            if ($variado != 0) {
                                echo $maximo_variado . ' em ' . $descricao_variado;
                            } else {
                                echo 'Sem dados';
                            }
                            ?></p>
        </div>
    </div>





</div>

<div class="container">
    
</div>