<div class="container mt-5" id="entrada">

   <div class="row">
      <div class="col-md-4">
         <p class="h3 text-center">Fixos</p>
         <p class="text-center tw-border">
            <?php
            echo ($this->view->gastos[0]['valor']);            
            ?>
         </p>
      </div>
      <div class="col-md-4">
         <p class="h3 text-center">Variados</p>
         <p class="text-center">
            <?php
               echo ($this->view->gastos[1]['valor']);
            ?>
         </p>
      </div>

      <div class="col-md-4">
         <p class="h3 text-center">Total</p>
         <p class="text-center">  
         <?php
               $total = 0;
               foreach($this->view->gastos as $key => $gastos){                  
                  $total += $gastos['valor'];                
               }
               echo $total;
            ?>                      
         </p>
      </div>
   </div>

   
   <div class="row mt-5">
      <div class="col-md-12 pt-4 pl-5 pr-5">
         <p class="h3 text-center">Adicionar Gastos</p>
         
         <form method="post" action="/gastos">
            <div class="row">
               <div class="col-md-4">
                  <p>Descrição</p>
                  <input type="text" class="form-control" name="descricao">
               </div>

               <div class="col-md-4">                  
                  <p>Valor</p>
                  <input type="number" step="0.01" class="form-control" name="valor">
               </div>

               <div class="col-md-4">
                  <p>Tipo</p>
                  <select class="form-select" name="tipo">
                     <option></option>
                     <option value="1">Fixo</option>
                     <option value="2">Variado</option>
                  </select>                  
               </div>  

               <div class="col-md-4 mt-4">
                  <p>Data</p>
                  <input type="date" class="form-control" name="data">
               </div>             
            
               <div class="col-auto mt-4">
                  <p>Pronto para registro</p>
                  <button class="btn btn-outline-light" style="color: pink">Registrar</button>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>