<div class="container mt-5" id="entrada">

   <p class="h5 border-bottom border-light">Data: <?php echo date('d/m/Y') ?></p>
   <br>
   <p>Abaixo encontram-se as somas dos gastos divididos por categoria.</p>
   
   <div class="row" data-anime="left">
      <div class="col-sm-4">
         <div class="card">
            <div class="card-body">
               <h5 class="card-title text-center">Gastos Fixos</h5>
               <p class="text-center mt-2 mb-1">
                  <?php
                  if (!empty($this->view->gastos) && ($this->view->gastos[0]['tipo'] == 1)) {
                     echo 'R$' . ($this->view->gastos[0]['valor']);
                  } else {
                     echo 'Sem dados';
                  }
                  ?>
               </p>
               <p class="card-text text-center"><small class="text-muted">Contas mensais</small></p>
            </div>
         </div>
      </div>

      <div class="col-sm-4">
         <div class="card">
            <div class="card-body">
               <h5 class="card-title text-center">Variados</h5>
               <p class="text-center mt-2 mb-1">
                  <?php
                  if (!empty($this->view->gastos) && ($this->view->gastos[0]['tipo'] == 2)){
                     echo 'R$' . ($this->view->gastos[0]['valor']);

                  } else if(!empty($this->view->gastos[1])){
                     echo 'R$' . ($this->view->gastos[1]['valor']);

                  }  else {
                     echo 'Sem dados';
                  }
                  ?>
               </p>
               <p class="card-text text-center"><small class="text-muted ">Lazer</small></p>
            </div>
         </div>
      </div>

      <div class="col-sm-4">
         <div class="card">
            <div class="card-body">
               <h5 class="card-title text-center">Total</h5>
               <p class="text-center mt-2 mb-1">
                  <?php
                  if (!empty($this->view->gastos[0]) && !empty($this->view->gastos[1])) {
                     echo 'R$' . (($this->view->gastos[0]['valor']) + ($this->view->gastos[1]['valor']));

                  } else if(!empty($this->view->gastos[0]) && empty($this->view->gastos[1])) {
                     echo 'R$' . ($this->view->gastos[0]['valor']);

                  } else if(empty($this->view->gastos[0]) && !empty($this->view->gastos[1])){
                     echo 'R$' . ($this->view->gastos[1]['valor']);

                  } else{
                     echo 'Sem dados';
                  }
                  ?>
               </p>
               <p class="card-text text-center"><small class="text-muted">Soma de tudo</small></p>
            </div>
         </div>
      </div>
   </div>

   <div class="row mt-5" id="formulario" data-anime="right">
      <div class="col-md-12 pt-4 pl-5 pr-5">
         <p class="h3 text-center border-bottom border-light">Adicionar Gastos</p>

         <form method="post" action="/salvar">
            <div class="row">
               <div class="col-md-4">
                  <p>Descrição</p>
                  <input type="text" class="form-control" name="descricao">
               </div>

               <div class="col-md-4">
                  <p>Valor</p>
                  <input type="number" step="0.01" class="form-control" name="valor">
               </div>

               <div class="col-md-4">
                  <p>Tipo</p>
                  <select class="form-select" name="tipo">
                     <option></option>
                     <option value="1">Fixo</option>
                     <option value="2">Variado</option>
                  </select>
               </div>

               <div class="col-md-4 mt-4">
                  <p>Data</p>
                  <input type="date" class="form-control" name="data">
               </div>

               <div class="col-auto mt-5">

                  <button class="btn btn-outline-light mt-3 mb-2" style="color: pink">Registrar</button>
               </div>
            </div>
         </form>
      </div>
   </div>
  
   <div class="row mt-5" data-anime="topo">
      <p class="h5">Explicações</p>
      <p>Gastos fixos: São os gastos que correspondem às dispesas mensais recorrentes e fixas, como contas de luz, água, aluguel, ou até mesmo fatura de cartão de crédito.</p>
      <p>Gastos Variados: São os gastos sobressalente e que podem deixar de existir ao longo do ano, como um jantar fora, compra de algo específico, viagens, ...</p>
      <p>Dentro de descrição colocar com o que foi gasto; de valor, o valor gasto; de tipo definir o tipo do gasto; e em data colocar a data que foi gasto</p>
   </div>
</div>