
<div class="container mt-5">

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Descricao</th>
      <th scope="col">Valor</th>
      <th scope="col">Tipo</th>
      <th scope="col">Data de Gasto</th>
      <th scope="col">Data gravamento</th>
    </tr>
  </thead>
  
  <tbody>
  <?php 
    $i = 0;
    foreach($this->view->gastos as $id_gastos => $gastos){ ?>
    <tr>
      <th scope="row"><?php echo $i; ?></th>
      <td><?php echo $gastos['descricao']; ?></td>
      <td><?php echo $gastos['valor']; ?></td>
      <td><?php echo $gastos['tipo']; ?></td>
      <td><?php echo $gastos['data']; ?></td>
      <td><?php echo $gastos['data_gravada']; ?></td>
    </tr>
    <?php $i++; }; ?>
  </tbody>

</table>

</div>