<div class="container mt-5">
    <?php if (empty($this->view->login)) { ?>
        <div class="row">
            <div class="col">
                <span class="text text-success"></span>
            </div>
        </div>
    <?php } else if (($this->view->login == 'erro')) { ?>
        <span class="text text-danger">E-mail ou senha inválido(s)</span>
    <?php }; ?>



    <div class="row border-bottom border-top border-light" id="topo">

        <div class="col-md-6 p-2 mb-2" data-anime="left">
            <p class="text-center h2"><strong>Gerencie seu dinheiro</strong></p>

            <div class="d-flex justify-content-center">
                <a href="/inscreverse" id="topo">
                    <button class="btn btn-outline-light">
                        Inscreva-se
                    </button>
                </a>
            </div>
        </div>

        <div class="col-md-5 mb-2" data-anime="right">

            <form class="form-group mt-3" action="/autenticar" method="post" id="entrar-form">
                <div class="d-flex justify-content-center mb-2">
                    <input type="text" class="form-control form-control-sm" name="email" placeholder="Usuário">
                </div>

                <div class="d-flex justify-content-center mb-2">
                    <input type="password" class="form-control form-control-sm" name="senha" placeholder="Senha">
                </div>

                <div class="d-flex justify-content-end">
                    <button class="btn btn-outline-light" style="color: pink">
                        Entrar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<main class="mt-4">
    <div class="pt-3" style="background: snow;">
        <div class="container" data-anime="topo">
            <h5 class='text-center' id="rosa15">Seja bem vindo à uma nova fase financeira da sua vida</h5>

            <div class="row">

                <div class="col-md-4 offset offset-1"><img src="img/gerenciar-patrimonio.jpg" alt="gerenciar-dinheiro" width="250px" class=""></div>

                <div class="col-md-6 mt-4 offset offset-1">
                    <p>Encontre no conforto de suas mãos o aplicativo ideal para anotar quando e como foi gasto seu dinheiro. </p>
                    <p class="text-center" id="rosa9">Gerencie seu dinheiro aqui!</p>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3" style="background: #f8e6e6">
        <div class="container pt-4 pb-1" data-anime="topo">
            <p>Anda perdido no fim do mês sem saber o que aconteceu com o dinheiro que tava no começo? Tinha feitos diversos planos para juntar mas, no fim, nada mais faz sentido? Nada melhor para encontrar o problema do que começar a anotar os gastos diários, da balinha na padaria às contas mensais.</p>
            <p>A solução está aqui. Um aplicativo de fácil entendimento, onde você encontrará a maneira de guardar seus gastos diários e, de quebra, comparar como está sendo gasto em um dashboard de fácil entendimento, além de possuir a relação completa em tabela. Celular, tablet e/ou computador com uma rede de internet conectada e pronto, ao fim do mês não haverá mais dúvidas de como o dinheiro foi gasto.</p>
            <p>Deixe a preguiça de lado e começe a realizar sonhos ao gerenciar seu tão suado dinheiro.</p>
            <p><a href="/inscreverse">Começe já!</a></p>
        </div>
    </div>

    <div class="mt-3 pt-3 pb-1" style="background: snow;">
        <div class="container" data-anime="topo">
            <p class="h4 text-center">Mas o que é <strong id="rosa4">gestão financeira?</strong></p>
            <p>Na marca assustadora de quase 72% as famílias brasileiras, em 2021, se encontraram endividados. Não se sinta envergonhado em ser um deles, mas está na hora de mudar tudo depende de você e só de você. Uma boa prática para começar a mudar este cenário está em gerir seu patrimônio.</p>
            <p>Gerir seu dinheiro nada mais é do que administra-lo ao longo do tempo. Mas como assim?</p>
            <p>Planejar, controlar, analisar e investir, nessas 4 palavrinhas de fácil entendimento mas difícil execução está o segredo de gerenciar seu dinheiro.</p>
            <p>Planeje como deve ser gastado ao longo do tempo, controle para não sair do planejamento, analise onde existem possibilidades de dimuir ou cortar os gastos e invista para proteger seu dinheiro da inflação e até mesmo cresce-lo, pronto, tudo se tornará mais colorido no fim do mês e menos desesperador. Durma tranquilo. </p>
            <p>Mantendo os gastos equilibrado ao longo do período estimado, ou seja, controlando o quanto sai em relação à quantidade que entra, há a possibilidade de 'lucrar' ao fim do mês, vendo em sua conta o saldo positivo em vez do zerado ou até mesmo do negativo. Para ter esse controle pode-se anotar tudo que está saindo, seja crédio ou débito, um gasto fixo ou variado, um luxo ou uma necessidade, para, no fim do mês, olhar e ter noção onde os gastos devem ser cortados ou diminuidos.</p>                        
        </div>
    </div>
</main>