<div class="container mt-5">

    <?php if (empty($this->view->login)) { ?>
        <div class="row">
            <div class="col">
                <span class="text text-success"></span>
            </div>
        </div>
    <?php } else if (($this->view->login == 'erro')) { ?>
        <span class="text text-danger">E-mail ou senha inválido(s)</span>
    <?php }; ?>



    <div class="row border-bottom border-top border-light mb-5" id="topo">

        <div class="col-md-6 p-2 mb-2">
            <p class="text-center h2">Gerencie seu patrimônio</p>

            <div class="d-flex justify-content-center">
                <a href="/inscreverse" id="topo">
                    <button class="btn btn-outline-light">
                        Inscreva-se
                    </button>
                </a>
            </div>
        </div>

        <div class="col-md-5">

            <form class="form-group mt-3" action="/autenticar" method="post" id="entrar-form">
                <div class="d-flex justify-content-center mb-2">
                    <input type="text" class="form-control form-control-sm" name="email" placeholder="Usuário">
                </div>

                <div class="d-flex justify-content-center mb-2">
                    <input type="password" class="form-control form-control-sm" name="senha" placeholder="Senha">
                </div>

                <div class="d-flex justify-content-end">
                    <button class="btn btn-outline-light" style="color: pink">
                        Entrar
                    </button>
                </div>
            </form>
        </div>
    </div>


    <main>
        <div class="row">
                <p class='h5'>Seja bem vindo à uma nova fase da sua vida, gerir suas economias.</p>
                <div class="col-md-8">
                    <p>Gerir seu patrimômio significa, basicamente, como controlar seu dinheiro. Facil de ser feito, aqui encontrá a ferramenta certa para anotar com o que está sendo gasto seu dinheiro para, no futuro, saber o que realmente aconteceu com ele e, assim, gerenciar não só o salário, mas também seus sonhos e necessidades que partem das finanças, como uma viagem, uma casa, um carro, ou até mesmo o churrasco do fim de semana.</p>
                </div>
                <div class="col-md-4">
                    <p>Pare de sofrer sem saber o que ta acontecendo e comece a perceber como os centavos estão indo embora e te afastando de subir de vida.</p>
                </div>    
        </div>
        <!--
        <div class="row mt-3">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-danger text-center">Investimentos</h5>
                        <p class="card-text text-success">Aprender sobre investimento pode parecer chato e difícil, até mesmo surreal, mas no século XXI tudo fica mais fácil, uma vez que o aprendizado está a apenas um clique do seu dedo. Busque aprender sobre investir e como manter seu patrimônio seguro do desgaste da inflação</p>
                        <a href="#" class="btn btn-primary"></a>
                    </div>
                </div>
            </div>
        </div>
        -->
    </main>
</div>