<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div>

            <div class="row">
                <div class="col">
                    <p class="h2 fw-bold" style="color: pink">Inscrever-se já!</p>
                </div>
            </div>

            <div class="row">
                <div class="col">

                    <form action="/registrar" method="post" id="inscreverse-form">
                        <div class="form-group mb-2">
                            <input name="nome" value="<?php echo $this->view->usuario['nome']; ?>" type="text" class="form-control" placeholder="Nome">
                        </div>

                        <div class="form-group mb-2">
                            <input name="email" value="<?php echo $this->view->usuario['email']; ?>" type="email" class="form-control" placeholder="E-mail">
                        </div>

                        <div class="form-group mb-2">
                            <input name="senha" type="password" class="form-control" placeholder="Senha">
                        </div>

                        <?php if ($this->view->erroCadastro) { ?>
                            <small class="form-text text-danger">Erro ao tentar realizar o cadastro, verifique se todos os campos foram preenchids corretamente.</small>
                        <?php }; ?>

                        <div class="mt-4 mb-4">
                            <small class="form-text">
                                Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                            </small>
                        </div>

                        <button class="btn btn-outline-light btn-block">
                            Inscrever-se
                        </button>
                       
                    </form>

                   
                    <a href="/" id="topo">
                        <button class="btn btn-outline-light btn-block">
                            Voltar
                        </button>
                    </a>
                       

                </div>
            </div>

        </div>

    </div>
</div>